// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vxokxnqdyzzgqdwxlebs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ4b2t4bnFkeXp6Z3Fkd3hsZWJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTEyNTc4NjIsImV4cCI6MjEwNjgzMzg2Mn0.NlRCuATCJRUa3oIuHpl2jc_0-ee2BTbFkY5gB0C2HJg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});